language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  global:
  - LINT_CHECK=0 ODOO_LINT=0 TESTS="0" VERSION="8.0" ODOO_REPO="vauxoo/odoo"

  matrix:
  - LINT_CHECK=1
  - ODOO_LINT=1
  - TESTS="1" UNIT_TEST="1"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-xlrd

install:
  - git clone --single-branch -b master-change-git-diff-jesuszapata --depth=1 https://github.com/vauxoo-dev/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - find ${HOME}/maintainer-quality-tools/travis -name test_flake8 -exec sed -i "s/get_modules/get_modules_changed/g" {} \;
  - find ${HOME}/maintainer-quality-tools/travis -name test_flake8 -exec sed -i "s/get_modules_changed(os.path.abspath('.')/get_modules_changed(os.path.abspath('.'), 'origin\/' \+ os.environ['TRAVIS_BRANCH']/g" {} \;
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  # get modules changed and set environment variable INCLUDE_LINT
  - PYTHONPATH=${PATH} python -c "import getaddons;print 'export INCLUDE_LINT=\"' + ' '.join(getaddons.get_modules_changed('${TRAVIS_BUILD_DIR}', 'origin/${TRAVIS_BRANCH}')) + '\"'" >${TRAVIS_BUILD_DIR}/modules_changed.profile
  - PYTHONPATH=${PATH} python -c "import os, getaddons;print 'export INCLUDE=\"' + ','.join(map(os.path.basename, getaddons.get_modules_changed('${TRAVIS_BUILD_DIR}', 'origin/${TRAVIS_BRANCH}'))) + '\"'" >>${TRAVIS_BUILD_DIR}/modules_changed.profile
  - source ${TRAVIS_BUILD_DIR}/modules_changed.profile
  # If there isn't modules changed for lint checks then exit
  - if [[ "x${INCLUDE_LINT}" == "x" && "${TESTS}" == "0" ]]; then exit 0; fi
  # Travis tests disabled. Travis can't download private repositories.
  - if [[ "${TESTS}" == "1" && "${RUNBOT}" != "1" ]]; then exit 0; fi
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
